# Generated by Django 5.2.5 on 2025-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lectures',
            field=models.ManyToManyField(blank=True, related_name='completed_by_enrollments', to='courses.lecture'),
        ),
    ]
