# Generated by Django 5.2.5 on 2025-09-12 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_completed_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
