# Generated by Django 5.2.5 on 2025-09-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question_course_category_course_is_free_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_by_enrollments', to='courses.lecture'),
        ),
    ]
