# Generated by Django 5.2.5 on 2025-09-14 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_last_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])]),
        ),
    ]
